FMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static #this is needed for file and image upload
from django.conf import settings
import fmsapp

# new imports
import cart
import shop
import orders


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('fmsapp.urls', namespace='fms') ),
    
    path ("orders/" , include('orders.urls' , namespace='order')),
    path ("shop/",include('shop.urls' , namespace='shop')),
    path ("cart/",include('cart.urls',namespace='cart')),
    path("blog/",include('blog.urls' , namespace='blog')),
    path("sales/",include('sales.urls' , namespace='sales')),
    # path('chapa-webhook', include('django_chapa.urls')),
    path('payment/',include('payment.urls' , namespace='payment'))
    
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fmsapp/urls.py
from django.urls import path
from . import views

app_name = 'fmsapp'

urlpatterns = [
    path('', views.Index.as_view(), name='index' ),
    path('administrator/login/', views.Login.as_view(), name='login'),
    path('administrator/register/', views.Register.as_view(), name='register'),
    path("dashboard/", views.Dashboard.as_view(), name="dashboard"),
    path("dashboard/logout/", views.Logout.as_view(), name="logout"),
    path("dashboard/administrator/edit/<int:pk>/", views.AccountUpdate.as_view(), name="account_update"),
    
    #orders
    path("dashboard/orders/all/",views.OrdersAll.as_view(), name="orders"),
   
   #Dam Routes

   path("dashboard/dam/new", views.DamNew.as_view(), name="create_dam"),
   path("dashboard/dam/", views.DamList.as_view(), name="all_dam"),
   path("dashboard/dam/<int:pk>/edit/", views.DamEdit.as_view(), name="dam_edit"),

   #Staff Path
   path("dashboard/staff/new/",views.StaffNew.as_view(), name="create_staff"),
   path("dashboard/staff/<int:pk>/single/", views.StaffSingle.as_view(), name="staff_single"),
   path("dashboard/staff/<int:pk>/edit/", views.StaffEdit.as_view(), name="staff_edit"),
   path("dashboard/staff/<int:pk>/delete/", views.StaffDestroy.as_view(), name="staff_delete"),
   path("dashboard/staff/", views.Staffers.as_view(), name="all_staff"),


   #Department Routes

   path("dashboard/department/new/",views.DepartmentNew.as_view(), name="create_dept"),
   path("dashboard/department/<int:pk>/single/",views.DepartmentDetail.as_view(), name="dept_single"),
   path("dashboard/department/<int:pk>/edit/",views.DepartmentUpdate.as_view(), name="dept_edit"),
   path("dashboard/department/<int:pk>/delete/",views.DepartmentDestroy.as_view(), name="dept_delete"),

   #Fish Routes
   path("dashboard/fish/add/",views.AddFish.as_view(), name="create_fish"),
   path("dashboard/fish/all/",views.ListFish.as_view(), name="all_fish"),
   path("dashboard/fish/<int:pk>/edit/",views.UpdateFish.as_view(), name="edit_fish"),
   path("dashboard/fish/<int:pk>/delete/",views.FishDestroy.as_view(), name="delete_fish"),

   #Harvest TimeLine
   path("dashboard/harvest/all/",views.AllHarvest.as_view(), name="harvests"),
   path("dashboard/harvest/add/",views.AddHarvest.as_view(), name="add_harvest"),
   path("dashboard/harvest/<int:pk>/edit/",views.EditHarvest.as_view(), name="edit_harvest"),
   path("dashboard/harvest/<int:pk>/delete/",views.DeleteHarvest.as_view(), name="delete_harvest"),
   path("dashboard/harvest/<int:pk>/single/",views.SingleHarvest.as_view(), name="single_harvest"),

   #Sales Routes
   path("dashboard/sales/all/",views.SalesAll.as_view(), name="sales"),
   path("dashboard/sales/add/",views.SalesAdd.as_view(), name="create_sale"),
   path("dashboard/sales/<int:pk>/edit/",views.SalesUpdate.as_view(), name="edit_sale"),
   path("dashboard/sales/<int:pk>/delete/",views.DeleteSales.as_view(), name="delete_sale"),

   #Credit Sales
   path("dashboard/credit-sales/all/",views.DebtorsAll.as_view(), name="debts"),
   path("dashboard/credit-sales/add/",views.DebtorsAdd.as_view(), name="create_debt"),
   path("dashboard/credit-sales/<int:pk>/edit/",views.DebtorsUpdate.as_view(), name="edit_debt"),
   path("dashboard/credit-sales/<int:pk>/delete/",views.DeleteDebtors.as_view(), name="delete_debt")

]

fmsapp/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import AbstractUser
# Create your models here.

class Dam (models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(blank=True)
    no_fishes = models.CharField(blank=True, max_length=100)
    fish_categories = models.CharField (blank=True, max_length=100)
    location = models.TextField(blank=True, max_length=700)
    about = models.TextField(blank=True, max_length=2000)

    def __str__(self):
        return self.name;
    

class Department (models.Model):
    name = models.CharField(max_length=15)
    description = models.TextField(max_length=700, default='Description goes here')

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("fms:dept_single", kwargs={"pk": self.pk})
    

class Staff (models.Model):
    STATES = (('edo','Edo'),('ekiti','Ekiti'),('kogi','Kogi'),('kwara','Kwara'),('lagos','Lagos'),
        ('ogun','Ogun'),('ondo','Ondo'),('osun','Osun'),('oyo','Oyo'),)
    image = models.ImageField(blank=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    stipend = models.CharField(max_length=10)
    mobile_number = models.CharField(max_length=11)
    state = models.CharField(max_length=20, choices=STATES, default='edo')
    country = models.CharField(max_length=20, default='Nigeria')
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True)
    work_description = models.TextField(max_length=1000)

    def __str__(self):
        return self.first_name+'-'+self.last_name

    def get_absolute_url(self):
        return reverse("fms:staff_single", kwargs={"pk": self.pk})
    
    

class User (AbstractUser):
    image = models.ImageField(blank=True)


class Fish(models.Model):
    name = models.CharField(max_length=50)
    types = models.CharField(max_length=50)
    total = models.IntegerField()
    immersiveDate = models.DateField(auto_now_add=True, null=True)
    HarvestDate = models.CharField(max_length=18, null=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

class TimeLine(models.Model):
    number = models.IntegerField()
    dam = models.CharField(max_length=2)
    others = models.TextField(max_length=9000)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Sales (models.Model):
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=120)
    slug = models.SlugField(max_length=100)
    image = models.ImageField(upload_to='products/%y/%m/%d', 
                              blank=True)
    description = models.TextField(blank=True)
    weight = models.IntegerField()
    amount = models.IntegerField()
    price = models.IntegerField()
    quantity = models.IntegerField()
    created = models.DateField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

class Debtors (models.Model):
    name = models.CharField(max_length=90)
    file_no = models.CharField(max_length=50)
    quantity = models.IntegerField()
    department = models.CharField(max_length=50)
    amount = models.IntegerField()
    signature = models.ImageField()
    created = models.DateField(auto_now_add=True, null=True)

fmsapp/views.py
from django.shortcuts import render,redirect,resolve_url
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.db.models import Sum
from django.contrib.auth import get_user_model,logout
from . models import Dam,Department,Staff, Fish, TimeLine,Debtors #Sales,
from django.contrib.auth.views import LoginView, TemplateView
from django.views.generic import CreateView,ListView,DetailView,UpdateView,View
from .forms import LoginForm, DamForm,StaffForm,DebtorsForm, DepartmentForm,RegisterForm,FishForm,HarvestForm,SalesForm

from shop.models import Product as Sales
from django.utils.text import slugify

from orders.models import Order
# Create your views here.


#This is the view used for desplaying the ordered lists


class OrdersAll(LoginRequiredMixin,ListView):
    login_url = 'fms:login'
    model = Order
    template_name = 'fmsapp/orders/index.html'
    context_object_name = 'orders'


class Index(TemplateView):
    template_name = 'fmsapp/home/index.html'
class Dashboard(LoginRequiredMixin,TemplateView):
    template_name = 'fmsapp/dashboard/index.html'
    login_url = 'fms:login'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["workerscount"] = Staff.objects.all().count()
        context["workers"] = Staff.objects.all()
        context['depts'] = Department.objects.all().count()
        context['fishes'] = Fish.objects.all().aggregate(Sum('total'))
        return context
    

# class Login(LoginView):
#     template_name = 'fmsapp/home/login.html'
#     form_class = LoginForm
#     model = get_user_model()
#     def get_success_url(self):
#         query = get_user_model().objects.get(pk=self.request.user.pk)
#         self.request.session['username'] = query.username
#         #self.request.session['']
#         url = resolve_url('fmsapp:dashboard')
#         return url

class Login(LoginView):
    template_name = 'fmsapp/home/login.html'
    form_class = LoginForm
    model = get_user_model()

    def get_success_url(self):
        user = self.request.user
        if user.is_superuser:
            url = resolve_url('fmsapp:dashboard')  # Redirect superuser to 'fmsapp:dashboard'
        else:
            url = resolve_url('sales:sales')  # Redirect regular users to 'sales:sales'

        return url

class Logout(View):
    def get(self,request):
        logout(request)
        return redirect('fmsapp:login', permanent=True)

class AccountUpdate(LoginRequiredMixin,UpdateView):
    login_url = 'fms:login'
    model = get_user_model()
    form_class = RegisterForm
    template_name = 'fmsapp/account.html'
    success_url = reverse_lazy('fmsapp:dashboard')

class Register(CreateView):
    template_name = 'fmsapp/home/signup.html'
    form_class = RegisterForm
    model = get_user_model()
    success_url =  reverse_lazy('fmsapp:login')


class DamNew(LoginRequiredMixin,CreateView):
    login_url = 'fms:login'
    model = Dam
    form_class = DamForm
    template_name = 'fmsapp/dam/create.html'
    success_url = reverse_lazy('fmsapp:all_dam')

class DamList(LoginRequiredMixin,ListView):
    model = Dam
    login_url = 'fms:login'
    template_name = 'fmsapp/dam/index.html'
    context_object_name = 'damlist'

class DamEdit(LoginRequiredMixin,UpdateView):
    model = Dam
    login_url = 'fms:login'
    template_name = 'fmsapp/dam/edit.html'
    form_class = DamForm
    success_url = reverse_lazy('fms:all_dam')    

#Staff Controller
class StaffNew(LoginRequiredMixin,CreateView):
    model  = Staff
    login_url = 'fms:login'
    form_class = StaffForm
    template_name = 'fmsapp/staff/create.html'
    
class StaffSingle(LoginRequiredMixin,DetailView):
    model = Staff
    login_url = 'fms:login'
    template_name = 'fmsapp/staff/single.html'
    context_object_name = 'staffer'

class Staffers(LoginRequiredMixin,ListView):
    model = Staff
    login_url = 'fms:login'
    template_name = 'fmsapp/staff/index.html'
    context_object_name = 'staffs'

class StaffEdit(LoginRequiredMixin,UpdateView):
    model =Staff
    login_url = 'fms:login'
    template_name = 'fmsapp/staff/edit.html'
    form_class =  StaffForm

class StaffDestroy (LoginRequiredMixin,View):
    login_url = 'fms:login'
    def get(self, request, pk):
        staff = Staff.objects.get(pk=pk)
        staff.delete()
        return redirect('fms:all_staff')
#Fish category



#Department Controller
class DepartmentNew(LoginRequiredMixin,CreateView):
    model = Department
    login_url = 'fms:login'
    form_class = DepartmentForm
    template_name  = 'fmsapp/department/create.html'

class DepartmentDetail(LoginRequiredMixin,DetailView):
    model = Department
    login_url = 'fms:login'
    template_name = 'fmsapp/department/index.html'
    context_object_name = 'dpt'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']
        staff = Staff.objects.filter(department=pk)
        context["staffer"] = staff 
        return context
    

class DepartmentUpdate(LoginRequiredMixin,UpdateView):
    model = Department
    login_url = 'fms:login'
    template_name = 'fmsapp/department/edit.html'
    form_class = DepartmentForm

class DepartmentDestroy(LoginRequiredMixin,View):
    login_url = 'fms:login'
    def get(self, request,pk):
        dept = Department.objects.get(pk=pk)
        dept.delete()
        return redirect('fms:dashboard')

#Fish Views

class AddFish(LoginRequiredMixin,CreateView):
    model = Fish
    login_url = 'fms:login'
    form_class = FishForm
    template_name = 'fmsapp/fish/create.html'
    success_url = reverse_lazy('fms:all_fish')

class UpdateFish(LoginRequiredMixin,UpdateView):
    model = Fish
    login_url = 'fms:login'
    form_class = FishForm
    template_name = 'fmsapp/fish/edit.html'
    success_url = reverse_lazy('fms:dashboard')

class ListFish(LoginRequiredMixin,ListView):
    model = Fish
    login_url = 'fms:login'
    template_name = 'fmsapp/fish/index.html'
    context_object_name = 'fishes'


class FishDestroy(LoginRequiredMixin,View):
    login_url = 'fms:login'
    def get(self, request,pk):
        fish = Fish.objects.get(pk=pk)
        fish.delete()
        return redirect('fms:dashboard')

#Harvest Views
class AllHarvest(LoginRequiredMixin,ListView):
    model = TimeLine
    login_url = 'fms:login'
    template_name = 'fmsapp/timeline/index.html'
    context_object_name = 'timelines'

class AddHarvest(LoginRequiredMixin,CreateView):
    login_url = 'fms:login'
    model = TimeLine
    template_name = 'fmsapp/timeline/create.html'
    form_class = HarvestForm
    success_url = reverse_lazy('fms:harvests')

class EditHarvest(LoginRequiredMixin,UpdateView):
    login_url = 'fms:login'
    model = TimeLine
    template_name = 'fmsapp/timeline/edit.html'
    form_class = HarvestForm
    success_url = reverse_lazy ('fms:harvests')


class DeleteHarvest(LoginRequiredMixin,View):
    login_url = 'fms:login'

    def get(self, request,pk):
        harvest = TimeLine.objects.get(pk=pk)
        harvest.delete()
        return redirect('fms:harvests')

class SingleHarvest(LoginRequiredMixin,DetailView):
    model = TimeLine
    login_url = 'fms:login'
    template_name = 'fmsapp/timeline/single.html'
    context_object_name = 'harvest'

# Sales All
class SalesAdd(LoginRequiredMixin,CreateView):
    model = Sales , 
    login_url = 'fms:login'
    form_class = SalesForm
    template_name = 'fmsapp/sales/create.html'
    success_url = reverse_lazy('fms:sales')

    def form_valid(self, form):
        sales = form.save(commit=False)
        sales.slug = slugify(sales.name)
        
        sales.save()
        return super().form_valid(form)
class SalesAll(LoginRequiredMixin,ListView):
    login_url = 'fms:login'
    model = Sales
    template_name = 'fmsapp/sales/index.html'
    context_object_name = 'sales'

class SalesUpdate (LoginRequiredMixin,UpdateView):
    model = Sales
    login_url = 'fms:login'
    form_class = SalesForm
    template_name = 'fmsapp/sales/edit.html'
    success_url = reverse_lazy ('fms:sales')

class DeleteSales(LoginRequiredMixin,View):
    login_url = 'fms:login'

    def get(self, request,pk):
        sale = Sales.objects.get(pk=pk)
        sale.delete()
        return redirect('fms:sales')

#Creditors/Debitors
class DebtorsAdd(LoginRequiredMixin,CreateView):
    model = Debtors
    login_url = 'fms:login'
    form_class = DebtorsForm
    template_name = 'fmsapp/credit/create.html'
    success_url = reverse_lazy('fms:debts')
class DebtorsAll(LoginRequiredMixin,ListView):
    model = Debtors
    login_url = 'fms:login'
    template_name = 'fmsapp/credit/index.html'
    context_object_name = 'debts'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["total"] = Debtors.objects.all().aggregate(Sum('amount'))
        return context
    

class DebtorsUpdate (LoginRequiredMixin,UpdateView):
    model = Debtors
    login_url = 'fms:login'
    form_class = DebtorsForm
    template_name = 'fmsapp/credit/edit.html'
    success_url = reverse_lazy ('fms:debts')

class DeleteDebtors(LoginRequiredMixin,View):
    login_url = 'fms:login'
    def get(self, request,pk):
        debt = Debtors.objects.get(pk=pk)
        debt.delete()
        return redirect('fms:debts')

fmsapp/templates/fmsapp/account.html
{% extends 'fmsapp/layout.html' %}
{% load static %}
{% block title %} Edit Administrator Information{% endblock title %}
{% block contents %}
    <section class="row">
        <div class="col-lg-6 offset-lg-3">
            <div class="card">
                <div class="card-body">
                <p class="text-center lead">Update Administrator Information</p><hr>
                    <form action="" class="form-group" method='POST' enctype='multipart/form-data'>
                        {% csrf_token %}
                        {{form.as_p}}
                        <button class="btn btn-success btn-block mt-3">Submit</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </section>
{% endblock contents %}

fmsapp/templates/fmsapp/footer.html
 <div class="row">
    <div class="col-md-12">
        <div class="copyright">
            <p>Copyright © 2023 Fish Farm Management System. All rights reserved.</p>
        </div>
    </div>
</div>

fmsapp/templates/fmsapp/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'fmsapp/vendor/font-awesome-5/css/fontawesome-all.min.css' %}">
    <!-- Title Page-->
    <title>{% block title %}{% endblock title %}</title>

    <!-- Fontfaces CSS-->
    <link href="{% static 'fmsapp/css/font-face.css' %}" rel="stylesheet" media="all">
     <link href="{% static 'fmsapp/css/custom.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'fmsapp/vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'fmsapp/vendor/font-awesome-5/css/fontawesome-all.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'fmsapp/vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="{% static 'fmsapp/vendor/bootstrap-4.1/bootstrap.min.css' %}" rel="stylesheet" media="all">

    <!-- {% static 'fmsapp/vendor CSS-->
    <link href="{% static 'fmsapp/vendor/animsition/animsition.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'fmsapp/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'fmsapp/vendor/wow/animate.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'fmsapp/vendor/css-hamburgers/hamburgers.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'fmsapp/vendor/slick/slick.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'fmsapp/vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'fmsapp/vendor/perfect-scrollbar/perfect-scrollbar.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'fmsapp/css/theme.css' %}" rel="stylesheet" media="all">

</head>

<body class="animsition">
    <div class="page-wrapper">
    <!-- MENU SIDEBAR-->
    {% include 'fmsapp/sidebar.html' %}
    <!-- END MENU SIDEBAR-->

        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- HEADER DESKTOP-->
            {% include 'fmsapp/navbar.html' %}  
            <!-- HEADER DESKTOP-->

            <!-- MAIN CONTENT-->
            <div class="main-content">
                {% block contents %}
                {% endblock contents %}
            </div>
            <!-- END MAIN CONTENT-->
            <!-- END PAGE CONTAINER-->
        </div>

    </div>

    <!-- Jquery JS-->
    <script src="{% static 'fmsapp/vendor/jquery-3.2.1.min.js' %}"></script>
    <!-- Bootstrap JS-->
    <script src="{% static 'fmsapp/vendor/bootstrap-4.1/popper.min.js' %}"></script>
    <script src="{% static 'fmsapp/vendor/bootstrap-4.1/bootstrap.min.js' %}"></script>
    <!-- {% static 'fmsapp/vendor JS       -->
    <script src="{% static 'fmsapp/vendor/slick/slick.min.js' %}">
    </script>
    <script src="{% static 'fmsapp/vendor/wow/wow.min.js' %}"></script>
    <script src="{% static 'fmsapp/vendor/animsition/animsition.min.js' %}"></script>
    <script src="{% static 'fmsapp/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js' %}">
    </script>
    <script src="{% static 'fmsapp/vendor/counter-up/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'fmsapp/vendor/counter-up/jquery.counterup.min.js' %}">
    </script>
    <script src="{% static 'fmsapp/vendor/circle-progress/circle-progress.min.js' %}"></script>
    <script src="{% static 'fmsapp/vendor/perfect-scrollbar/perfect-scrollbar.js' %}"></script>
    <script src="{% static 'fmsapp/vendor/chartjs/Chart.bundle.min.js' %}"></script>
    <script src="{% static 'fmsapp/vendor/select2/select2.min.js' %}">
    </script>

    <!-- Main JS-->
    <script src="{% static 'fmsapp/js/main.js' %}"></script>
    {% block skript %}
    {% endblock skript %}

</body>

</html>
<!-- end document-->

fmsapp/templates/fmsapp/navbar.html
<header class="header-desktop bg-primary text-light">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="header-wrap">
                            <div></div>
                            <div class="header-button">
                               
                                <div class="account-wrap">
                                    <div class="account-item clearfix js-item-menu">
                                        <div class="image">
                                            {% comment %} <img src="{{request.user.image.url}}" alt="{{request.session.username}}" /> {% endcomment %}
                                        </div>
                                        <div class="content">
                                            {{request.session.username | upper}}
                                        </div>
                                        <div class="account-dropdown js-dropdown">
                                            <div class="info clearfix">
                                                <div class="image">
                                                        {% comment %} <img src="{{request.user.image.url}}" alt="{{user.username}}" /> {% endcomment %}
                                                </div>
                                                <div class="content">
                                                    <h5 class="name">
                                                        {{user.username | capfirst}}
                                                    </h5>
                                                    
                                                </div>
                                            </div>
                                            <div class="account-dropdown__body">
                                                <div class="account-dropdown__item">
                                                    <a href="{% url 'fmsapp:account_update' pk=user.pk %}">
                                                        <i class="zmdi zmdi-account"></i>Account</a>
                                                </div>
                                              
                                            </div>
                                            <div class="account-dropdown__footer">
                                                <a href="{% url 'fmsapp:logout' %}">
                                                    <i class="zmdi zmdi-power"></i>Logout</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

fmsapp/templates/fmsapp/sidebar.html
{% load static %}
<aside class="menu-sidebar d-none d-lg-block bg-dark text-light">
            <div class="logo bg-primary text-light">
                <a href='fmsapp:dashboared' class="text-light">
                    CHMSC FISH FARM MANAGEMENT SYSTEM
                </a>
            </div>
            <div class="menu-sidebar__content js-scrollbar1">
                <nav class="navbar-sidebar">
                    <ul class="list-unstyled navbar__list">
                        <li class="active has-sub ">
                            <a class="js-arrow" href="/dashboard" >
                                <i class="fas fa-tachometer-alt"></i>Dashboard</a>
                            
                        </li>
                        <li>
                            <a href="{% url 'fms:all_dam' %}">
                                <i class="fas fa-chart-bar"></i>Dam</a>
                        </li>
                         <li class="has-sub">
                            <a class="js-arrow" href="#"><i class="far fa-copy"></i>Departments</a>
                                <a href=" {% url 'fms:create_dept' %}"> <i class="fas fa-plus"> </i> New Department</a>
                            <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                              {% for d in dept  %}
                                <li>
                                    <a href="{% url 'fms:dept_single' pk=d.id %}">{{d.name}} </a>
                                </li>
                              {% endfor %}
                            </ul>
                        </li>
                        <li>
                            <a href="{% url 'fms:all_staff' %}">
                               <i class="fas fa-user"></i>Staff / Workers</a>
                        </li>
                        <li>
                            <a href="{% url 'fms:register' %}">
                               <i class="fas fa-user"></i>New User</a>
                        </li>
                        <li>
                            <a href="{% url 'fms:all_fish' %}">
                                <i class="fas fa-archive"></i>Fish Record</a>
                        </li>

                         <li>
                            <a href="{% url 'fms:sales' %}">
                                <i class="far fa-folder"></i>Sales</a>
                        </li>
                        <li>
                            <a href="{% url 'fms:orders' %}">
                                <i class="far fa-folder"></i>Orders</a>
                        </li>

                        <li>
                            <a href="{% url 'fms:debts' %}">
                                <i class="fas fa-database"></i>Credit Sales</a>
                        </li>

                        <li>
                            <a href="{% url 'fms:harvests' %}">
                                <i class="fas fa-clock"></i>Harvest Timeline</a>
                        </li>
                        
                      
                    </ul>
                </nav>
            </div>
        </aside>